baseURL = "https://open-de-roazhon-2020.now.sh/"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = "Open de Roazhon 2020 v2"
theme = "ezhil"

copyright = "© Copyright notice"

# Enable syntax highlighting.
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
# googleAnalytics = "UA-123-45"
# Your Disqus sortname.
# disqusShortname = "localhost"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10

enableGitInfo = true

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "Tournois de discgolf PDGA/FFFD C-Tier le 17-18 octobre 2020 sur le parcours de la Prévalaye"

    # Content types which are included in home page recent posts list.
    mainSections = ["posts", "page"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true

    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "icons/myicon.png"

    # Switch to dark mode or auto detect mode from OS (Optional).
    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
    mode = "auto" # "dark" or "auto"

    # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
    # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
    # you can specify custom css path as `css/custom.css`.
    customCSS = "css/style.css"
    # Custom CSS added to dark mode style.
    # customDarkCSS = "css/custom-dark.css"

    # Custom list of Javascript files to load. Just like custom CSS you can place js files under
    # `static/js` folder and specify path here as `js/script-name.js`. You can also specify full url,
    # for example you may want to include external JS library.
    # customJS = ["js/abc.js", "js/xyz.js", "https://code.jquery.com/jquery-3.4.1.js"]

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1


[[menu.main]]
name = "Livret Joueur"
url = "/livret-joueur"
weight = 4

[[menu.main]]
name = "Le parcours"
url = "/parcours"
weight = 5


[[menu.main]]
name = "À Propos"
url = "/a-propos"
weight = 7

[[menu.main]]
name = "Infos pratiques"
url = "/infos"
weight = 6


[[menu.main]]
name = "Discgolfmetrix"
url = "https://discgolfmetrix.com/1476129"
weight = 8


# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/genuinegreg/discgolf-open-de-roazhon-2020"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/Mr-Friz-Disc-Golf-Rennes-347602635615270"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

# Enable tags.
[taxonomies]
   tag = "tags"
